services:
  mariadb:
    image: mariadb:11.3
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: taller
      MYSQL_USER: talleruser
      MYSQL_PASSWORD: tallerpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./backend/database/init-wordpress.sql:/docker-entrypoint-initdb.d/init-wordpress.sql
    networks:
      - taller_net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - mariadb
    networks:
      - taller_net

  backend:
    build: ./backend
    container_name: backend
    restart: always
    depends_on:
      - mariadb
    environment:
      DB_CONNECTION: mariadb
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_DATABASE: taller
      DB_USERNAME: talleruser
      DB_PASSWORD: tallerpass
      APP_ENV: local
      APP_DEBUG: "true"
      APP_URL: http://localhost:8000
    ports:
      - "8000:80"
    volumes:
      - ./backend/storage:/var/www/html/storage
      - ./backend/.env:/var/www/html/.env
    command: ["sh", "/var/www/html/entrypoint.sh"]
    networks:
      - taller_net

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "4200:80"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    networks:
      - taller_net

  wordpress:
    build: ./wordpress
    container_name: wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppass
      WORDPRESS_DB_NAME: wpdb
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME', 'http://localhost:8081');
        define('WP_SITEURL', 'http://localhost:8081');
        define('WP_DEBUG', false);
        define('FS_METHOD', 'direct');
    ports:
      - "8081:80"
    volumes:
      - ./wordpress/html:/var/www/html
      - ./wordpress/import:/import
      - ./wordpress/init:/docker-entrypoint-initwp.d
    depends_on:
      - mariadb
    networks:
      - taller_net

volumes:
  db_data:

networks:
  taller_net:
    driver: bridge
