services:
  mariadb:
    image: mariadb:11.3
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: taller
      MYSQL_USER: talleruser
      MYSQL_PASSWORD: tallerpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - taller_net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - mariadb
    networks:
      - taller_net

  backend:
    build: ./backend
    container_name: backend
    restart: always
    depends_on:
      - mariadb
    environment:
      DB_CONNECTION: mariadb
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_DATABASE: taller
      DB_USERNAME: talleruser
      DB_PASSWORD: tallerpass
      APP_ENV: local
      APP_DEBUG: "true"
      APP_URL: http://localhost:8000
    ports:
      - "8000:80"
    volumes:
            - ./backend:/var/www/html
    command: ["sh", "/var/www/html/entrypoint.sh"]
    networks:
      - taller_net

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    networks:
      - taller_net

volumes:
  db_data:

networks:
  taller_net:
    driver: bridge