version: '3.8'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx_certs:/etc/nginx/certs:rw
      - nginx_vhost:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
    networks:
      - taller_net

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: acme-companion
    restart: always
    depends_on:
      - nginx-proxy
    environment:
      - DEFAULT_EMAIL=hugales2005@gmail.com
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx_certs:/etc/nginx/certs:rw
      - nginx_vhost:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
    networks:
      - taller_net

  mariadb:
    image: mariadb:11.3
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: taller
      MYSQL_USER: talleruser
      MYSQL_PASSWORD: tallerpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - taller_net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - mariadb
    networks:
      - taller_net

  backend:
    build: ./backend
    container_name: backend
    restart: always
    depends_on:
      - mariadb
    environment:
      DB_CONNECTION: mariadb
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_DATABASE: taller
      DB_USERNAME: talleruser
      DB_PASSWORD: tallerpass
      APP_ENV: local
      APP_DEBUG: "true"
      APP_URL: http://backend:80
    volumes:
      - ./backend:/var/www/html
    command: ["sh", "/var/www/html/entrypoint.sh"]
    networks:
      - taller_net

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    depends_on:
      - backend
    environment:
      VIRTUAL_HOST: tallermatehtorres.zapto.org
      LETSENCRYPT_HOST: tallermatehtorres.zapto.org
      LETSENCRYPT_EMAIL: hugales2005@gmail.com
    volumes:
      - ./frontend:/app
    networks:
      - taller_net

volumes:
  db_data:
  nginx_certs:
  nginx_vhost:
  nginx_html:

networks:
  taller_net:
    driver: bridge